name: First Workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: windows-latest
    steps:
      - name: Print Greeting
        run: echo " hello"
      - name: Good bye
        run: echo "bye"
        
